# -*- coding: utf-8 -*-
"""empleados.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15Oluef-xoVQPDnPpu8aNdEQTfjEa1lT0
"""

import streamlit as st
import pandas as pd
import datetime

# Archivo donde se guardarán los datos
FILE_NAME = "personal_limpieza.csv"
ASISTENCIA_FILE = "asistencia.csv"

# Cargar datos existentes
def load_data(file_name):
    try:
        return pd.read_csv(file_name)
    except FileNotFoundError:
        return pd.DataFrame(columns=["Nombre", "Apellidos", "Cédula", "Localidad", "Fecha Ingreso", "Fecha Nacimiento"])

# Guardar datos
def save_data(df, file_name):
    df.to_csv(file_name, index=False)

# Interfaz de Streamlit
st.title("Gestión de Personal de Limpieza")

# Opción de registro de nuevo personal
st.header("Registro de Personal")
with st.form("registro_form"):
    nombre = st.text_input("Nombre")
    apellidos = st.text_input("Apellidos")
    cedula = st.text_input("Cédula")
    localidad = st.text_input("Localidad")
    fecha_ingreso = st.date_input("Fecha de Ingreso", datetime.date.today())
    fecha_nacimiento = st.date_input("Fecha de Nacimiento")
    submit_button = st.form_submit_button("Registrar")

if submit_button:
    df_personal = load_data(FILE_NAME)
    nuevo_registro = pd.DataFrame([[nombre, apellidos, cedula, localidad, fecha_ingreso, fecha_nacimiento]],
                                  columns=df_personal.columns)
    df_personal = pd.concat([df_personal, nuevo_registro], ignore_index=True)
    save_data(df_personal, FILE_NAME)
    st.success("Personal registrado exitosamente")

# Opción para control de asistencia
st.header("Registro de Asistencia")
df_personal = load_data(FILE_NAME)
if not df_personal.empty:
    personal_seleccionado = st.selectbox("Seleccionar Personal", df_personal["Cédula"].tolist())
    hora_ingreso = st.time_input("Hora de Ingreso", datetime.datetime.now().time())
    if st.button("Registrar Asistencia"):
        df_asistencia = load_data(ASISTENCIA_FILE)
        nuevo_asistencia = pd.DataFrame([[personal_seleccionado, hora_ingreso]], columns=["Cédula", "Hora Ingreso"])
        df_asistencia = pd.concat([df_asistencia, nuevo_asistencia], ignore_index=True)
        save_data(df_asistencia, ASISTENCIA_FILE)
        st.success("Asistencia registrada exitosamente")
else:
    st.warning("No hay personal registrado aún.")